//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateExpertCVFollowupDetail
    {
        public int ID { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public string ProcessStart { get; set; }
        public string ResumePreparation { get; set; }
        public string ResumeVerification { get; set; }
        public string ResumeModification { get; set; }
        public string RUC { get; set; }
        public string ProcessEnd { get; set; }
    }
}
