//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateMaster()
        {
            this.CandidateMarketingDetails = new HashSet<CandidateMarketingDetail>();
            this.CandidateMarketingDetails1 = new HashSet<CandidateMarketingDetail>();
            this.CandidateTechnicalExpertDetails = new HashSet<CandidateTechnicalExpertDetail>();
            this.CandidateTechnicalExpertDetails1 = new HashSet<CandidateTechnicalExpertDetail>();
            this.CandidateTimeLines = new HashSet<CandidateTimeLine>();
            this.CandidateTimeLines1 = new HashSet<CandidateTimeLine>();
            this.CommentDetails = new HashSet<CommentDetail>();
            this.CommentDetails1 = new HashSet<CommentDetail>();
            this.FollowUpMasters = new HashSet<FollowUpMaster>();
            this.FollowUpMasters1 = new HashSet<FollowUpMaster>();
            this.MarketingRevenueDetails = new HashSet<MarketingRevenueDetail>();
            this.MarketingRevenueDetails1 = new HashSet<MarketingRevenueDetail>();
            this.RecurringMasters = new HashSet<RecurringMaster>();
            this.RecurringMasters1 = new HashSet<RecurringMaster>();
            this.RequestMasters = new HashSet<RequestMaster>();
            this.RequestMasters1 = new HashSet<RequestMaster>();
        }
    
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> RefSalesAssociate { get; set; }
        public int RefRecurringTypeId { get; set; }
        public int RefServiceId { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public System.DateTime Date { get; set; }
        public string PaymentStatus { get; set; }
        public string CandidateStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> MarketingStartDate { get; set; }
        public string VisaStatus { get; set; }
        public int TechnologyId { get; set; }
        public Nullable<bool> AgreementSent { get; set; }
        public Nullable<decimal> Agreement { get; set; }
        public string AgreementLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateMarketingDetail> CandidateMarketingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateMarketingDetail> CandidateMarketingDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateTechnicalExpertDetail> CandidateTechnicalExpertDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateTechnicalExpertDetail> CandidateTechnicalExpertDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateTimeLine> CandidateTimeLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateTimeLine> CandidateTimeLines1 { get; set; }
        public virtual RecurringType RecurringType { get; set; }
        public virtual RecurringType RecurringType1 { get; set; }
        public virtual UserAccountDetail UserAccountDetail { get; set; }
        public virtual UserAccountDetail UserAccountDetail1 { get; set; }
        public virtual SalesServiceMaster SalesServiceMaster { get; set; }
        public virtual SalesServiceMaster SalesServiceMaster1 { get; set; }
        public virtual TechnologyMaster TechnologyMaster { get; set; }
        public virtual TechnologyMaster TechnologyMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentDetail> CommentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentDetail> CommentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpMaster> FollowUpMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpMaster> FollowUpMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketingRevenueDetail> MarketingRevenueDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketingRevenueDetail> MarketingRevenueDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringMaster> RecurringMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringMaster> RecurringMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestMaster> RequestMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestMaster> RequestMasters1 { get; set; }
    }
}
