//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateAssignLog
    {
        public int ID { get; set; }
        public Nullable<int> AssignFrom { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.TimeSpan> AssignTime { get; set; }
    }
}
