//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long Id { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorURL { get; set; }
        public Nullable<System.DateTime> Timest { get; set; }
    }
}
