//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpMasterLog
    {
        public int Id { get; set; }
        public string FollowUpMessage { get; set; }
        public string FollowUpBy { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<System.DateTime> FollowUpAddDate { get; set; }
    }
}
